### ISSUE TITLE
你好，能分享下wangeditor5 扩展的音频功能吗？

### ISSUE THREAD

**Issue by jysunshine** [BB-zhan/bigint-Transfrom#1]

**Comment by BB-zhan** [comment]
> 

因为公司需求不方便分享，可以参考
https://github.com/wangeditor-team/wangEditor/issues/4644
https://github.com/wangeditor-team/wangEditor/issues/4152
就能拼凑出完整的答案

**Comment by BB-zhan** [comment]
多看看wangEditor的模组源码和video模组做成模组，然后多尝试一下就拼出来了

**Comment by jysunshine** [comment]
好的好的，多谢 正在看，
就是看着有点费劲~


一米阳光
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BB-zhan/BB_zhan-s-SelfNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 中午1:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BB-zhan/BB_zhan-s-SelfNet] 你好，能分享下wangeditor5 扩展的音频功能吗？ (Issue #1)





   
因为公司需求不方便分享，可以参考
 wangeditor-team/wangEditor#4644
 wangeditor-team/wangEditor#4152
 就能拼凑出完整的答案

**Comment by jysunshine** [comment]
你好 你能帮我看下这里写的哪里不对吗？
现在可以插入文件了但是报错了， editor.getHtml()也获取不到audio的html









一米阳光
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BB-zhan/BB_zhan-s-SelfNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 中午1:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BB-zhan/BB_zhan-s-SelfNet] 你好，能分享下wangeditor5 扩展的音频功能吗？ (Issue #1)





 
多看看wangEditor的模组源码和video模组做成模组，然后多尝试一下就拼出来了

**Comment by BB-zhan** [comment]
> 

我这边啥也看不见啊

**Comment by BB-zhan** [comment]
> 你好 你能帮我看下这里写的哪里不对吗？ 现在可以插入文件了但是报错了， editor.getHtml()也获取不到audio的html 一米阳光 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "BB-zhan/BB_zhan-s-SelfNet" ***@***.***&gt;; 发送时间:&nbsp;2022年11月3日(星期四) 中午1:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [BB-zhan/BB_zhan-s-SelfNet] 你好，能分享下wangeditor5 扩展的音频功能吗？ (Issue #1) 多看看wangEditor的模组源码和video模组做成模组，然后多尝试一下就拼出来了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

![1667466225620](https://user-images.githubusercontent.com/109065366/199682160-73fb7178-4159-4c87-aee8-206d50f6cdd2.png)

**Comment by jysunshine** [comment]
你好，能加你一个微信或qq。或给我一个邮箱地址？


一米阳光
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BB-zhan/BB_zhan-s-SelfNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 下午5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BB-zhan/BB_zhan-s-SelfNet] 你好，能分享下wangeditor5 扩展的音频功能吗？ (Issue #1)





  
你好 你能帮我看下这里写的哪里不对吗？ 现在可以插入文件了但是报错了， editor.getHtml()也获取不到audio的html 一米阳光 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "BB-zhan/BB_zhan-s-SelfNet" @.&gt;; 发送时间:&nbsp;2022年11月3日(星期四) 中午1:46 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [BB-zhan/BB_zhan-s-SelfNet] 你好，能分享下wangeditor5 扩展的音频功能吗？ (Issue #1) 多看看wangEditor的模组源码和video模组做成模组，然后多尝试一下就拼出来了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;

**Comment by BB-zhan** [comment]
> 你好，能加你一个微信或qq。或给我一个邮箱地址？ 一米阳光 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "BB-zhan/BB_zhan-s-SelfNet" ***@***.***&gt;; 发送时间:&nbsp;2022年11月3日(星期四) 下午5:04 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [BB-zhan/BB_zhan-s-SelfNet] 你好，能分享下wangeditor5 扩展的音频功能吗？ (Issue #1) 你好 你能帮我看下这里写的哪里不对吗？ 现在可以插入文件了但是报错了， editor.getHtml()也获取不到audio的html 一米阳光 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "BB-zhan/BB_zhan-s-SelfNet" @.&gt;; 发送时间:&nbsp;2022年11月3日(星期四) 中午1:46 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [BB-zhan/BB_zhan-s-SelfNet] 你好，能分享下wangeditor5 扩展的音频功能吗？ (Issue #1) 多看看wangEditor的模组源码和video模组做成模组，然后多尝试一下就拼出来了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

c66_99

**Comment by linuxzcy** [comment]
您好 我按照你的写法为什么不行呢？有没有demo呢

**Comment by jysunshine** [comment]
您好，我已收到，尽快给您回复。
